# Generated by Django 6.1.1 on 2026-10-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('subcontractor', 'Subkontraktor'), ('supervisor', 'Supervisor Lapangan / Koordinator Supervisor'), ('hse_officer', 'HSE Officer'), ('hse_coordinator', 'HSE Coordinator'), ('project_manager', 'Project Manager')], max_length=30),
        ),
    ]
