# Generated by Django 6.1.1 on 2026-10-04 20:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HIRADocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('document_date', models.DateField(default=django.utils.timezone.localdate)),
                ('external_procedure_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_officer', 'Menunggu HSE Officer'), ('pending_pm', 'Menunggu Project Manager'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('cancelled', 'Dibatalkan')], default='draft', max_length=20)),
                ('submission_round', models.PositiveSmallIntegerField(default=0)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hira_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hira_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hira_documents', to='projects.project')),
            ],
            options={
                'verbose_name': 'HIRA Document',
                'verbose_name_plural': 'HIRA Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HIRAGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_function', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('hira_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='hira.hiradocument')),
            ],
            options={
                'verbose_name': 'HIRA Group',
                'verbose_name_plural': 'HIRA Groups',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HIRAApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('hse_officer', 'HSE Officer'), ('project_manager', 'Project Manager')], max_length=20)),
                ('decision', models.CharField(choices=[('approved', 'Disetujui'), ('rejected', 'Ditolak')], max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('submission_round', models.PositiveSmallIntegerField()),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hira_decisions', to=settings.AUTH_USER_MODEL)),
                ('hira_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='hira.hiradocument')),
            ],
            options={
                'ordering': ['decided_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('decision', 'approved'), models.Q(('remarks', ''), _negated=True), _connector='OR'), name='hira_rejection_requires_remarks')],
            },
        ),
        migrations.CreateModel(
            name='HIRAActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('activity_name', models.CharField(max_length=255)),
                ('activity_type', models.CharField(choices=[('R', 'Rutin'), ('NR', 'Non Rutin'), ('E', 'Emergency')], max_length=2)),
                ('potential_hazard', models.TextField()),
                ('risk_impact', models.TextField()),
                ('applicable_regulation', models.TextField(blank=True)),
                ('existing_controls', models.TextField(blank=True)),
                ('opportunity', models.TextField(blank=True)),
                ('initial_severity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('initial_likelihood', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('initial_score', models.PositiveSmallIntegerField(editable=False)),
                ('initial_category', models.CharField(choices=[('R', 'Rendah'), ('M', 'Menengah'), ('T', 'Tinggi'), ('E', 'Ekstrem')], editable=False, max_length=1)),
                ('initial_acceptable', models.BooleanField(editable=False)),
                ('residual_severity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('residual_likelihood', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('residual_score', models.PositiveSmallIntegerField(editable=False)),
                ('residual_category', models.CharField(choices=[('R', 'Rendah'), ('M', 'Menengah'), ('T', 'Tinggi'), ('E', 'Ekstrem')], editable=False, max_length=1)),
                ('residual_acceptable', models.BooleanField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='hira.hiragroup')),
            ],
            options={
                'verbose_name': 'HIRA Activity',
                'verbose_name_plural': 'HIRA Activities',
                'ordering': ['order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('initial_severity__range', (1, 5)), ('initial_likelihood__range', (1, 5)), ('residual_severity__range', (1, 5)), ('residual_likelihood__range', (1, 5))), name='hira_activity_scores_1_to_5')],
            },
        ),
    ]
