# Generated by Django 6.1.1 on 2026-10-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hira', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiradocument',
            old_name='title',
            new_name='work_area',
        ),
        migrations.AddField(
            model_name='hiraactivity',
            name='control_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hiradocument',
            name='work_package',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
